flavors/standard-EXASOL-6.1.0/flavor_base/base_test_deps/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/build_run/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/flavor_base_deps/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.1.0/flavor_base/language_deps/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/udfclient_deps/Dockerfile
- add --no-install-recommends
- remove file /exaudf/external/bazel_tools/
- add python*-setuptools to the required packages
part of #35
=> Cleanup standard flavor 6.1

.current_gitmodules, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages
- Fix install scripts 
- for empty package lists
- for lines starting with a comment but without space after #
- Reorganize /ext/scripts directory
- Add tests for list_insalled scripts
- Update apt packages minor versions, because old version are no more available
=>  Fix install scripts for empty package lists

flavors/standard-EXASOL-6.0.0/flavor_base/flavor_base_deps/packages/pip_packages, flavors/standard-EXASOL-6.1.0/flavor_base/flavor_base_deps/packages/pip_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/udfclient_deps/packages/apt_get_packages
Update:
- software-properties-common
- libssl-dev
- python-boto
- python3-boto
Pin:
- azure-storage to 0.36.0, because 0.37.0 changes the package structure and this needs more investigation, before an update is possible. https://pypi.org/project/azure-storage/0.37.0/
=> Update and pin dependency versions

.current_gitmodules, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages
Solves #67 
Additional changes:
- Refactoring of emit python_ext_dataframe.cc 
- Additional error codes for python_ext_dataframe.cc
- Explicit error message for dataframes with datetime64 columns which are not datetime64[ns]
- Additional tests for single column dataframe emits
- Exclude tests/test directory from duplicate error code search
- Update some Ubuntu packages because the old versions are not available anymore
=> Fix error when emitting only one Timestamp column in a dataframe

.github/workflows/nigthly.yaml
- We use a scheduled GitHub Actions to trigger a complete rebuild on Google Cloud Build
- We cannot use GitHub Actions, because the VMs do not provide enough disk space
- We trigger the rebuild by creating a new branch with the prefix `rebuild/nightly_` and a new empty commit it this branch. Afterwards, we are pushing this branch to GitHub and trigger with it the Google Cloud Build.
- The GitHub Action is schedule for 1am every day
Closes #73
=> Add GitHub action trigger for nightly rebuilds

flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages
Updated apt-packages:
python-pip: 9.0.1-2.3~ubuntu1.18.04.2 -> 9.0.1-2.3~ubuntu1.18.04.3
python-pip: 9.0.1-2.3~ubuntu1.18.04.2 -> 9.0.1-2.3~ubuntu1.18.04.3
python-samba: 2:4.7.6+dfsg~ubuntu-0ubuntu2.19 -> 2:4.7.6+dfsg~ubuntu-0ubuntu2.20
Fixes #108
=> Update apt-packages for standard-EXASOL-7.0.0

flavors/standard-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages
=> Update openjdk-11-jdk-headless for standard flavor 6.2 and 7.0

flavors/standard-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages
Updated packages:
unzip|6.0-21ubuntu1|6.0-21ubuntu1.1
python-lxml|4.2.1-1ubuntu0.2|4.2.1-1ubuntu0.3
python3-lxml|4.2.1-1ubuntu0.2|4.2.1-1ubuntu0.3
Fixes #155
=> Update apt dependencies for standard flavors 6.2 and 7.0

.current_gitmodules
The exit code of the python script was hidden by the pipe to tee. I added `set -o pipefail` before running the python script to get the exit code of the failing command in the pipe.
Fixes exasol/script-languages-release#167
=> Fix the exit code of the exaslct start script

.current_gitmodules, flavors/standard-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages
```
Package                |Old Version              |New Version
openjdk-11-jdk-headless|11.0.9.1+1-0ubuntu1~18.04|11.0.10+9-0ubuntu1~18.04
```
Fixes #178
=> Update ubuntu package openjdk-11-jdk-headless from to 11.0.10+9-0ubuntu1~18.04

flavors/standard-EXASOL-6.1.0/flavor_base/flavor_base_deps/packages/pip_packages, flavors/standard-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/pip_packages, flavors/standard-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/pip_packages, flavors/standard-EXASOL-7.0.0/flavor_base/udfclient_deps/packages/apt_get_packages
* Pin rsa python package to 4.5 for python2
* Update libssl-dev from 1.1.1-1ubuntu2.1~18.04.7 to 1.1.1-1ubuntu2.1~18.04.8
Fixes #185 
Fixes #182
=> Update and pin packages in standard flavors

.current_gitmodules, flavors/standard-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages
* Add `rendered_line_transformation_functions` to template generation for package list, to modify lines after they were rendered with the templates. 
* Refactored package management scripts to use `rendered_line_transformation_functions` to remove remaining template placeholder if versions are not specified, especially if this removal has conditions, such as the package is specified as URL
* Add GitHub actions workflow to test package management scripts
Fixes #213
=>  Add option --allow-no-version-for-urls for install_via_pip.pl

flavors/standard-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages
Fixes #247 
```
package|old|new
openjdk-11-jdk-headless|11.0.10+9-0ubuntu1~18.04|11.0.11+9-0ubuntu2~18.04
python-samba|2:4.7.6+dfsg~ubuntu-0ubuntu2.21|2:4.7.6+dfsg~ubuntu-0ubuntu2.23
```
=> Update apt package for standard flavors

.current_gitmodules, README.md, exaslct_src, flavors/r-3.5-data-science-EXASOL-6.2.0/flavor_base/build_steps.py, flavors/r-4.0-minimal-EXASOL-6.2.0/flavor_base/build_steps.py, flavors/standard-EXASOL-6.2.0/flavor_base/build_steps.py, flavors/standard-EXASOL-7.0.0/flavor_base/build_steps.py, flavors/standard-EXASOL-7.1.0/flavor_base/build_steps.py
- Replace exaslct implementation with starter scripts of exasol/script-languages-container-tool
- Note: Using the exalsct from exasol/script-languages-container-tool changes the imports of the build_steps.py of the flavors
- Note: The exaslct starter scripts use a Docker container to run exalsct to reduce the required dependency
- Remove detailed User Guide from Readme and link to User Guide of exasol/script-languages-container-tool
- Improve Readme text
Fixes #243
Fixes #66
Closes  #65
=> Remove exaslct implementation and replace it by the starter scripts of exasol/script-languages-container-tool

flavors/standard-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/pip3_packages, flavors/standard-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/pip_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/pip3_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/pip_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/python2_pip_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/python3_pip_packages
RCA:
exasol/websocket-api#21
removed Python2.7 support which broke CI builds.
Solution:
We need to pin version of websocket-api to last working version.
=> #278: Exasol WebSocket change broke CI builds

.current_gitmodules, README.md
Due to https://github.com/exasol/script-languages-container-tool/issues/48
exaslct needs to be updated in order to be compatible with bash 4.2.
Fixes #281.
=> #281:Update exaslct

doc/changes/changes-2.4.0.md
=> #355: Prepared documentation for release 2.4.0

.current_gitmodules, doc/changes/changes-2.5.0.md, doc/changes/package_diffs/2.5.0/README.md, doc/changes/package_diffs/2.5.0/standard-EXASOL-7.1.0-without-python2.7/flavor_base_deps/python3_pip_packages_diff.md, doc/changes/package_diffs/2.5.0/standard-EXASOL-7.1.0/flavor_base_deps/python3_pip_packages_diff.md, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/flavor_base_deps/packages/python3_pip_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/python3_pip_packages
=> #366 Add the SageMaker Python SDK to the standard flavors

.current_gitmodules, doc/changes/changes-3.1.0.md
RCA:
1. pip install with --no-cache-dir works, no cache is beeing created
2. pip installation itself creates already a cache dir with 2 packages: 'http' and 'selfcheck'
3. "pip list" also creates a pip cache
Solution:
1. Remove cache directory after pip installation (No option was found to suppress creation of cache directory during pip installation)
2. Apply no-cache-dir for pip list
=> #395: Avoid creating wheel cache in install_via_pip

doc/changes/changes-4.3.0.md, flavors/standard-EXASOL-8.0.0/flavor_base/build_run/Dockerfile
Removed the source of udfclient only from Standard-8.0.0 container!
=> #433: Removed the source of the udflclient from the standard containers

.current_gitmodules, doc/changes/changes-4.3.0.md, doc/changes/package_diffs/4.3.0/python-3.6-data-science-cuda-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/python-3.6-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/python-3.7-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/python-3.8-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/r-4-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/standard-EXASOL-7.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/standard-EXASOL-7.1.0-without-python2.7/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/standard-EXASOL-7.1.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/standard-EXASOL-8.0.0/build_deps/apt_get_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/build_deps/packages/apt_get_packages
`locales` packages was duplicated in step `build-deps` in all flavors
Also added a validation in generate_package_diffs_for_flavors.py
Note that the package diff markdown still contain two entries for package `locales`, this is due to the fact that the last release (4.2.0) already had this issue and thus it is not wrong if both packages appear in the docu.
Fixes #599 
=> #599: Fixed duplicated packages

doc/changes/changes-4.3.0.md
=> #632: Prepared release 4.3.0

.current_gitmodules, doc/changes/changes_8.1.0.md
=> #902: fixed memory related bugs with emit dataframe

.github/workflows/update_trivy_cache.yaml, doc/changes/changes_8.4.0.md
=> #1002: Use ECR fallback repository for Trivy caching

.current_gitmodules, doc/changes/changes_8.4.0.md
=> #958: Fix conda version conflict

.current_gitmodules, doc/changes/changes_9.0.0.md, doc/changes/package_diffs/9.0.0/standard-EXASOL-all/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/standard-EXASOL-all/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/standard-EXASOL-all/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-8-python-3.10-cuda-conda__template-Exasol-all-python-3.10-cuda-conda/conda_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-java-17/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-java-17/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-python-3.10-conda/conda_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-python-3.10/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-python-3.10/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-python-3.10/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-r-4/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.0.0/template-Exasol-all-r-4/language_deps/apt_get_packages_diff.md, flavors/standard-EXASOL-all/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-all/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/standard-EXASOL-all/flavor_base/language_deps/packages/apt_get_packages, flavors/template-Exasol-all-r-4/flavor_base/build_deps/packages/apt_get_packages, flavors/template-Exasol-all-r-4/flavor_base/language_deps/packages/apt_get_packages
=> #1019: Update Dependencies on top of 8.3.0 

.current_gitmodules, doc/changes/changes_9.0.0.md, flavors/standard-EXASOL-all/flavor_customization/Dockerfile, flavors/standard-EXASOL-all/flavor_customization/packages/r_cran_packages
fixes #772 
Also fixed the sample R package in flavor customization step.
=> #772: Added check of installation of R packages

.current_gitmodules, doc/changes/changes_9.1.0.md, flavors/standard-EXASOL-all/flavor_base/security_scan/trivy.rego, flavors/template-Exasol-all-r-4/flavor_base/security_scan/trivy.rego, poetry.lock
=> #1029: Extended trivy rego for Kernel CVE's

.current_gitmodules, doc/changes/changes_9.2.0.md
=> #1060: fix pandas memory leak tests and prepare release

.current_gitmodules, doc/changes/changes_9.7.0.md
closes #1146 
2. [x] Have you thought about version number? If there is a breaking change in the toolchain, need to update major version.
3. [x] If you plan a release, have you checked the Exasol packages for updates?
=> #1146: Reverted the trivy-ignore for CVE-2025-47273

.current_gitmodules, doc/changes/changes_10.1.0.md
=> #1094: Removed ssl dependency
