exasol/script-languages-release

.current_gitmodules, docker_db_config
This reverts commit db889f083c94d915ad72c907feb0666a50d5a6fa.
=> Revert "Support multiple docker db versions for tests (#7)"

.current_gitmodules, exaudfclient/extension/BUILD, exaudfclient/extension/build_local_all.sh, exaudfclient/extension/rcontainer/BUILD, flavors/fancyr-EXASOL-6.0.0/flavor_base/build_deps/Dockerfile, flavors/fancyr-EXASOL-6.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/fancyr-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile, flavors/fancyr-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.0.0/flavor_base/build_deps/Dockerfile, flavors/standard-EXASOL-6.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages
solves https://github.com/exasol/script-languages-release/issues/13
=> Add alwayslink to cc_library and pin Bazel to version 1.0.0

.current_gitmodules, exaudfclient/extension/.bazelrc, exaudfclient/extension/BUILD, flavors/fancyr-EXASOL-6.0.0/flavor_base/base_test_build_run/Dockerfile, flavors/fancyr-EXASOL-6.0.0/flavor_base/flavor_test_build_run/Dockerfile, flavors/fancyr-EXASOL-6.1.0/flavor_base/base_test_build_run/Dockerfile, flavors/fancyr-EXASOL-6.1.0/flavor_base/flavor_test_build_run/Dockerfile, flavors/standard-EXASOL-6.0.0/flavor_base/base_test_build_run/Dockerfile, flavors/standard-EXASOL-6.0.0/flavor_base/flavor_test_build_run/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/base_test_build_run/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/flavor_test_build_run/Dockerfile
and fix missing buckets and conf directory in base_test_build_run images
=> Use same exaudfclient execitable name for fast binary and slow wrapper

.current_gitmodules, flavors/fancyr-EXASOL-6.0.0/flavor_base/build_deps/Dockerfile, flavors/fancyr-EXASOL-6.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/fancyr-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile, flavors/fancyr-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.0.0/flavor_base/build_deps/Dockerfile, flavors/standard-EXASOL-6.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.1.0/flavor_base/build_deps/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/build_deps/packages/apt_get_packages
=> Download bazel dep-package from Github releases

.current_gitmodules, flavors/fancyr-EXASOL-6.0.0/flavor_base/build_run/Dockerfile, flavors/fancyr-EXASOL-6.1.0/flavor_base/build_run/Dockerfile, flavors/standard-EXASOL-6.0.0/flavor_base/build_run/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/build_run/Dockerfile
=> Fix linking of libjvm to fix Java UDF crash

.current_gitmodules, flavors/standard-EXASOL-6.1.0/flavor_base/flavor_base_deps/packages/pip3_packages
=> Add the exasol websocket-api to Python3 in the standard flavor

.current_gitmodules, pipenv_utils.sh
Bug Fixes:
- curl calls use --silent --show-error if we need to parse the result of request
- Fix output in error case of command_log_handler.py 
- Replace manual docker client creation in Task by DockerBaseTask where it was missing
- Increase docker socket timeout
- Exclude Docker test environment from cleanup if should be reused or started via cli command spawn-test-environment
- Fix triggers for Google Cloud Build CI Job 
Refactoring:
- Extract pipenv_utils.sh from exaslct start script
Google Cloud Build CI Job for exaslct tests:
- Add distinction between local test execution and Google Cloud Build, because Google Cloud Build runs the tests in a docker container with the host docker socket mounted in and this produce some issues with host volumes and networking
- Add initial tests for …
=> EXASLCT: bug fixes, refactoring and CI Job for tests

.current_gitmodules
solves https://github.com/exasol/script-languages-release/issues/31
=> Java EMITS UDF Scripts cannot emit null

.current_gitmodules
fixes https://github.com/exasol/script-languages/issues/113
=> Improve shutdown handling of the UDFClient in error cases

.current_gitmodules, google-cloud-build/.env/env.template.yaml, google-cloud-build/README.md, google-cloud-build/ci-scripts/build_master_branch.yaml, google-cloud-build/ci-scripts/export.yaml, google-cloud-build/ci-scripts/rebuild_branch.yaml, google-cloud-build/ci-scripts/release.yaml, google-cloud-build/download_config.sh, google-cloud-build/update_triggers.sh
https://github.com/exasol/script-languages/pull/123
=>  Fixes and improvements on Google Cloud Build CI Setup

.current_gitmodules, flavors/fancyr-EXASOL-6.0.0/flavor_base/release/Dockerfile, flavors/fancyr-EXASOL-6.1.0/flavor_base/release/Dockerfile, flavors/standard-EXASOL-6.0.0/flavor_base/release/Dockerfile, flavors/standard-EXASOL-6.1.0/flavor_base/release/Dockerfile, flavors/standard-EXASOL-7.0.0/flavor_base/release/Dockerfile
=> Copy /var from language_deps and flavor_customization to release step

.github/workflows/check_if_submodules_head_are_ancestors_of_origin_master.yaml
=> Add pull-request blocker which checks if the HEAD of submodules is at a ancestor of origin/master

.current_gitmodules, .github/workflows/check_for_rebuild_branch.sh, .github/workflows/check_for_rebuild_branch.yml, google-cloud-build/triggers/flavor-config/rebuild_branch/python3-ds-EXASOL-6.0.0.yaml, google-cloud-build/triggers/flavor-config/rebuild_branch/python3-ds-EXASOL-6.1.0.yaml, google-cloud-build/triggers/flavor-config/rebuild_branch/python3-ds-cuda-preview-EXASOL-6.1.0.yaml
=> Add a build breaker to the CI which fails if the commit was not rebuild without cache

flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages
```
python-cryptography|2.1.4-1ubuntu1.3 -> python-cryptography|2.1.4-1ubuntu1.4
python-samba|2:4.7.6+dfsg~ubuntu-0ubuntu2.20 -> python-samba|2:4.7.6+dfsg~ubuntu-0ubuntu2.21
```
=> Update apt packages

.current_gitmodules
=> Make the --path-in-bucket commandline argument optional for the upload command

flavors/standard-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages
=> Update ubuntu package python2.7-dev from 2.7.17-1~18.04ubuntu1.2 to 2.7.17-1~18.04ubuntu1.5

.current_gitmodules, doc/changes/changelog.md, doc/changes/changes-1.0.1.md, google-cloud-build/ci-scripts/build_branch.yaml, google-cloud-build/ci-scripts/build_master_branch.yaml, google-cloud-build/ci-scripts/build_pull_request.yaml, google-cloud-build/ci-scripts/export.yaml, google-cloud-build/ci-scripts/rebuild_branch.yaml, google-cloud-build/ci-scripts/release.yaml
=> #120: Increased queueTTL for google cloud build

.current_gitmodules, .github/workflows/check_current_gitmodules.yaml
=> Add script to list candidate versions for pip

flavors/r-4.0-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/udfclient_deps/packages/apt_get_packages
=> Update ubuntu package libssl-dev from 1.1.1-1ubuntu2.1~18.04.8 to 1.1.1-1ubuntu2.1~18.04.9

.current_gitmodules
Update script-languages to fix echo timestamp unit test.
=> #235:Fixed echo timestamp unit test.

.current_gitmodules, doc/changes/changes-2.2.0.md
=> #293: Removed python-distutils-extra package from python-3.6-minimal-EXASOL-6.2.0

doc/changes/changes-2.2.0.md
=> #138: Removed duplicated line in ExaWrapper.java

.current_gitmodules, .github/pull_request_template.md, doc/changes/changes-2.2.0.md
=> #308: Update script-language-container-tool to version 0.2.1

.current_gitmodules, doc/changes/changes-2.2.0.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/udfclient_deps/packages/apt_get_packages
* #312: Updated libssl
Update version to 1.1.1-1ubuntu2.1~18.04.10
on all affected script languages containers.
Fixes #312
=> Features/#312/update libssl (#314)

.current_gitmodules, doc/changes/changes-2.2.0.md
=> #317: Using temporary file for the install script in install_via_r_remotes.pl

.current_gitmodules, doc/changes/changes-2.4.0.md
=> #342 Specify python2 for bazel steps

.current_gitmodules, doc/changes/changes-3.0.0.md
=> #386 fix network test for r 4 minimal

doc/changes/changes-3.0.0.md
=> #391: Prepare documentation for release 3.0.0

doc/changes/changes-3.1.0.md, doc/changes/package_diffs/3.1.0/r-4-minimal-EXASOL-6.2.0/flavor_base_deps/apt_get_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages
=> #422: Remove maven from r-4-minimum flavor

doc/changes/changes-3.2.0.md, doc/changes/package_diffs/3.2.0/r-3.5-data-science-EXASOL-6.2.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/3.2.0/standard-EXASOL-6.2.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/3.2.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/3.2.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/3.2.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, flavors/r-3.5-data-science-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages
=> #437 updated openjdk 11 jdk headless

.current_gitmodules, doc/changes/changes-3.2.0.md
=> #440: Updated exaslct to 0.8.0

.current_gitmodules, doc/changes/changes-3.2.0.md
=> #441: updated to exasol python test framework 0.3.0

.current_gitmodules, doc/changes/changes-3.2.0.md
=> #453: Ignore CVE-2021-33430 on Python3.6 flavors

.current_gitmodules, doc/changes/changes-3.2.0.md
=> #454: java udf conditional compilation

doc/changes/changes-3.2.0.md
=> Add release date

doc/changes/changes-3.3.0.md, doc/changes/package_diffs/3.3.0/standard-EXASOL-7.0.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/3.3.0/standard-EXASOL-7.1.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/3.3.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #478 update standard container packages

.current_gitmodules, doc/changes/changes-4.1.0.md
=> #344: Removed log file exaudfclient/base/file.txt

.current_gitmodules, doc/changes/changes-4.1.0.md
=> #150: Removed usage of pip legacy dependency resolver

.current_gitmodules, doc/changes/changes-4.1.0.md, doc/changes/package_diffs/4.1.0/python-3.8-minimal-EXASOL-6.2.0/udfclient_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-6.2.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-8.0.0/udfclient_deps/apt_get_packages_diff.md, flavors/standard-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/udfclient_deps/packages/apt_get_packages
=> #517: Updated openjdk-11-jdk-headless and libssl-dev

flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages_r
=> #522: Update Ubuntu libexpat packages

doc/changes/changes-4.1.0.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/4.1.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_r_diff.md, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #525: Update package libxml2-dev on standard-8.0 flavor

doc/changes/changes-4.1.0.md
=> #533: Prepared release 4.1.0

.gitignore, README.md, doc/changes/changes-4.2.0.md, doc/user_guide/usage.md, doc/user_guide/user_guide.md, doc/user_guide/vagrant.md, vagrant/Vagrantfile, vagrant/provisioning/dns.sh, vagrant/provisioning/install.sh, vagrant/provisioning/install_poetry.sh, vagrant/provisioning/resize-disk.sh
=> #542: Add vagrant setup for libvirt

.current_gitmodules, doc/changes/changes-4.2.0.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.0.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-8.0.0/flavor_base/security_scan/.trivyignore
=> #553: Ignored CVE-2022-23648

.current_gitmodules, doc/changes/changes-4.2.0.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.0.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-8.0.0/flavor_base/security_scan/.trivyignore
=> Merge to Master

doc/changes/changes-4.2.0.md, doc/changes/package_diffs/4.2.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/4.2.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md
=> #578: Prepared release 4.2.0

doc/changes/changes-4.3.0.md, doc/user_guide/usage.md
=> #78: Added Docker socket section to prerequisites in usage documentation

doc/changes/changes-4.3.0.md, doc/user_guide/usage.md
=> #107: Referenced EXA_toolbox.upload_github_release_file_to_bucketfs in docu

doc/changes/changes-4.3.0.md, doc/user_guide/usage.md
=> #22: Added documentation about testing

doc/changes/changes-4.3.0.md, doc/user_guide/FAQ.md, doc/user_guide/user_guide.md
=> #161: Created FAQ and added solution for /tmp directory

doc/changes/changes-4.3.0.md, doc/changes/package_diffs/4.3.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #605: updated packages

.current_gitmodules, aws-code-build/DeveloperGuide.md, aws-code-build/build_config.json, aws-code-build/ci/build_buildspec.yaml, aws-code-build/ci/buildspec.yaml, aws-code-build/release/build_buildspec.yaml, aws-code-build/release/buildspec.yaml, aws-code-build/run_local, aws-code-build/update_aws_build_stack.sh, githooks/install.sh, githooks/pre-commit, githooks/update_aws_buildspec.sh, poetry.lock, pyproject.toml
=> #502: moved ci to aws code build

.current_gitmodules, doc/changes/changes-4.3.0.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.0.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-8.0.0/flavor_base/security_scan/.trivyignore
=> #613: Ignored CVE-2022-29581

.github/workflows/push_docker_test_container.yaml, doc/changes/changes-4.3.0.md
=> #573: Pushed test container to Dockerhub

doc/changes/changes-4.3.0.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/Dockerfile, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/trivy-secret.yaml
=> #620: Fixed trivy false positive during secret scan

.github/workflows/release_droid_upload_github_release_assets.yml, .github/workflows/test_release.yml, doc/changes/changes-4.3.0.md
=> #628: Added release GH actions

.current_gitmodules, doc/changes/changes-4.3.0.md, doc/changes/package_diffs/4.3.0/python-3.6-minimal-EXASOL-6.2.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/python-3.7-minimal-EXASOL-6.2.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/python-3.8-minimal-EXASOL-6.2.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/r-4-minimal-EXASOL-6.2.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/4.3.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages
=> #636: Updated Ubuntu packages

.github/workflows/release_droid_upload_github_release_assets.yml, doc/changes/changelog.md, doc/changes/changes_4.3.0.md
=> #638: Adapted changelog to release-droid format

.github/workflows/nigthly.yaml, doc/changes/changes_5.0.0.md
=> #650: Changed nightly cron and avoid running nightly builds during the weekend

.current_gitmodules, doc/changes/changes_5.0.0.md
=> #572: Refactored package import tests

.current_gitmodules, doc/changes/changes_5.0.0.md
Fixes #666 
Changes:
* Add derived_from config to package_diffs script
* Add CI for package diff script
* Fix duplicate in package list
* Add --compare-to-commit option to package-diff script and set CI to compare to master
* Use subprocess.run(check=True) for git operations
=> #666: Make package diffs more robust for CI

doc/changes/changes_5.0.0.md, poetry.lock, pyproject.toml
=> #679: Added a duplicated pyproject.toml

doc/changes/changes_5.0.0.md, doc/changes/package_diffs/5.0.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #683: updated smb packages

.current_gitmodules, doc/changes/changes_5.0.0.md, doc/changes/package_diffs/5.0.0/template-Exasol-all-python-3.8-conda__python-3.8-minimal-EXASOL-6.2.0/README.md, doc/changes/package_diffs/5.0.0/template-Exasol-all-python-3.8-conda__python-3.8-minimal-EXASOL-6.2.0/build_deps/conda_packages_diff.md
=> 686#: fixed bazel crashes on conda flavor

doc/changes/changes_5.0.0.md, doc/changes/package_diffs/5.0.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/5.0.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/5.0.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/5.0.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/5.0.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages
=> #690: updated openjdk and libxml2-dev

doc/changes/changes_5.0.0.md
=> Prepare release 5.0.0

doc/changes/changes_5.0.0.md
=> Changed release summary and moved #590 in changelog

doc/changes/changes_5.0.0.md
=> Prepare release 5.0.0 (#694)

.github/workflows/check_version.yaml, doc/changes/changelog.md, doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/README.md, poetry.lock, pyproject.toml
=> #697: Disabled version check GH action for master branch

.current_gitmodules, doc/changes/changes_6.0.0.md
=> #703: Fixed package diff workflow

.current_gitmodules, doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/python-3.7-minimal-EXASOL-6.2.0/language_deps/apt_get_packages_python_diff.md
=> #713: Updated Python3.7

.current_gitmodules, doc/changes/changes_6.0.0.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.0.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-8.0.0/flavor_base/security_scan/.trivyignore
=> #727: Ignored CVE-2022-23960

doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/README.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, flavors/standard-EXASOL-7.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages
=> #731: Update openjdk for standard flavor

doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/README.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, flavors/standard-EXASOL-7.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages
=> Update master branch

.current_gitmodules, doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_r_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages_r, flavors/standard-EXASOL-8.0.0/flavor_base/security_scan/.trivyignore
=> #734: Ignored CVE-2022-43945

doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_r_diff.md, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages_r
=> #737 updated ubuntu packages

doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/README.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #752 update ubuntu packages

.current_gitmodules, doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/python-3.7-minimal-EXASOL-6.2.0/udfclient_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/python-3.8-minimal-EXASOL-6.2.0/udfclient_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/r-4-minimal-EXASOL-6.2.0/udfclient_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/udfclient_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/udfclient_deps/apt_get_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/udfclient_deps/packages/apt_get_packages
=> #756 updated Ubuntu packages

.current_gitmodules, doc/changes/changes_6.0.0.md, doc/changes/package_diffs/6.0.0/python-3.7-minimal-EXASOL-6.2.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/python-3.8-minimal-EXASOL-6.2.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/r-4-minimal-EXASOL-6.2.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0-without-python2.7/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.0.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #759 update ubuntu packages

.current_gitmodules, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/flavor_base_deps/packages/python3_pip_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/flavor_base_deps/packages/python3_pip_packages, flavors/standard-EXASOL-7.1.0-without-python2.7/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/flavor_base_deps/packages/python3_pip_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/udfclient_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_python/packages/python3_pip_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages
=> #762: Updated ubuntu/pip packages

.current_gitmodules, doc/changes/changes_6.0.0.md, exaudfclient/extension/rcontainer/exascript_r_wrap.R
=> #754: Fixed R SCALAR RETURNS UDFs with empty run function hangs

.current_gitmodules, doc/changes/changes_6.1.0.md, doc/changes/package_diffs/6.1.0/python-3.7-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/python-3.8-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/r-4-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/standard-EXASOL-7.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/standard-EXASOL-7.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/standard-EXASOL-7.1.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/standard-EXASOL-7.1.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/standard-EXASOL-8.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/6.1.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-7.1.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages
=> #800: Updated Ubuntu packages

.current_gitmodules, doc/changes/changes_7.0.0.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-conda/language_deps/conda_packages_diff.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-conda/udfclient_deps/conda_packages_diff.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-cuda-conda/language_deps/conda_packages_diff.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-cuda-conda/udfclient_deps/conda_packages_diff.md
=>  #831: Update conda flavors to cryptography 41.0.3 and openssl 3.1.2 

doc/changes/changes_7.0.0.md, doc/changes/package_diffs/7.0.0/r-4-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/7.0.0/standard-EXASOL-8.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/7.0.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/7.0.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-8.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/security_scan/.trivyignore
=> #839: Updated dependencies and ignore Kernel CVEs

.current_gitmodules, doc/changes/changes_7.0.0.md, doc/changes/package_diffs/7.0.0/r-4-minimal-EXASOL-6.2.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/7.0.0/standard-EXASOL-8.0.0/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/7.0.0/standard-EXASOL-8.0.0/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/7.0.0/standard-EXASOL-8.0.0/language_deps/apt_get_packages_diff.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-conda/language_deps/conda_packages_diff.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-conda/udfclient_deps/conda_packages_diff.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-cuda-conda/language_deps/conda_packages_diff.md, doc/changes/package_diffs/7.0.0/template-Exasol-all-python-3.8-cuda-conda/udfclient_deps/conda_packages_diff.md, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/build_deps/packages/apt_get_packages, flavors/r-4-minimal-EXASOL-6.2.0/flavor_base/security_scan/.trivyignore, flavors/standard-EXASOL-8.0.0/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/language_deps/packages/apt_get_packages, flavors/standard-EXASOL-8.0.0/flavor_base/security_scan/.trivyignore
=> Merge into develop into master

.current_gitmodules, aws-code-build/ci/buildspec.yaml, aws-code-build/release/buildspec.yaml, doc/changes/changes_7.2.0.md
=> #877: Added tests using a module-based Java UDF

.current_gitmodules, doc/changes/changes_8.1.0.md, doc/changes/package_diffs/8.1.0/standard-EXASOL-all/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/8.1.0/template-Exasol-all-java-17/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/8.1.0/template-Exasol-all-python-3.10/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/8.1.0/template-Exasol-all-r-4__r-4-minimal-EXASOL-6.2.0/flavor_base_deps/apt_get_packages_diff.md, flavors/standard-EXASOL-all/flavor_base/flavor_base_deps_apt/packages/apt_get_packages, flavors/template-Exasol-all-java-17/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/template-Exasol-all-r-4/flavor_base/flavor_base_deps/packages/apt_get_packages
=> #906: Updated APT package

.current_gitmodules, doc/changes/changes_8.1.0.md, doc/changes/package_diffs/8.1.0/template-Exasol-all-python-3.10-conda__template-Exasol-all-python-3.8-conda/udfclient_deps/conda_packages_diff.md, doc/changes/package_diffs/8.1.0/template-Exasol-all-python-3.10-cuda-conda__template-Exasol-all-python-3.8-cuda-conda/udfclient_deps/conda_packages_diff.md
=> #908 pined conda package

.github/workflows/push_docker_test_container.yaml, doc/changes/changes_8.1.0.md
=> #895: Fixed GH Action 'Publish Docker Test Container'

.current_gitmodules, doc/changes/changes_8.1.0.md, flavors/standard-EXASOL-all/flavor_base/build_deps/Dockerfile, flavors/standard-EXASOL-all/flavor_base/build_deps/packages/apt_get_packages, flavors/standard-EXASOL-all/flavor_base/language_deps/packages/apt_get_packages, flavors/template-Exasol-all-java-17/flavor_base/build_deps/packages/apt_get_packages, flavors/template-Exasol-all-java-17/flavor_base/language_deps/packages/apt_get_packages, flavors/template-Exasol-all-r-4/flavor_base/build_deps/packages/apt_get_packages
fixes https://github.com/exasol/script-languages-release/issues/917
=> #917: Updated Ubuntu JDK package

doc/changes/changelog.md, doc/changes/changes_8.3.0.md, pyproject.toml, release_config.yml
=> #933: Added file release_config.yml

.current_gitmodules
=> Added unit test for option line parser

.github/workflows/push_docker_test_container.yaml, doc/changes/changes_8.4.0.md
=> #965: Fixed Publish Docker Test Container GH workflow

.current_gitmodules, doc/changes/changes_8.4.0.md
- closes #982 - Added a performance test for ScriptOptions parser for a single line UDF
- closes #983 - Refactor CTPG script options Java parser code
=> Refactoring ScriptOptions parser

.current_gitmodules, doc/changes/changes_8.4.0.md, exaudfclient/exaudfclient.cc
- #986: Added environment variable for new ScriptOptionsLine parser in UDF client
- #990: Forward JAR options without changing order to classpath
- #989: Trim script class and import script options
- #993: Added escape sequence for backslash in new Script Options parser
=> Refactorings Script Options Parser

.github/workflows/validate_pr.yaml
=> Fixed pr validation job

doc/changes/changes_9.1.0.md, flavors/README.md, poetry.lock
=> prepare release 9.1.0

.current_gitmodules, doc/changes/changes_9.1.0.md, doc/changes/package_diffs/9.1.0/standard-EXASOL-all/flavor_base_deps_python/python3_pip_packages_diff.md, flavors/standard-EXASOL-all/flavor_base/flavor_base_deps_python/packages/python3_pip_packages
=> Fixes release date and updated exasol-bucketfs dependency

flavors/standard-EXASOL-all/flavor_base/language_definitions.json
=> Fixed language_definitions.json

doc/changes/changes_9.3.0.md
=> Prepared release

doc/changes/changes_9.6.0.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-java-11/security_scan/apt_get_packages_trivy_deps_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-java-11/security_scan/apt_get_packages_trivy_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-java-17/security_scan/apt_get_packages_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-java-17/security_scan/apt_get_packages_trivy_deps_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-python-3.10/security_scan/apt_get_packages_trivy_deps_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-python-3.10/security_scan/apt_get_packages_trivy_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-r-4.4/security_scan/apt_get_packages_trivy_deps_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-r-4.4/security_scan/apt_get_packages_trivy_diff.md, flavors/standard-EXASOL-all-java-11/flavor_base/security_scan/Dockerfile, flavors/standard-EXASOL-all-java-11/flavor_base/security_scan/packages/apt_get_packages_trivy, flavors/standard-EXASOL-all-java-11/flavor_base/security_scan/packages/apt_get_packages_trivy_deps, flavors/standard-EXASOL-all-java-17/flavor_base/security_scan/Dockerfile, flavors/standard-EXASOL-all-java-17/flavor_base/security_scan/packages/apt_get_packages, flavors/standard-EXASOL-all-java-17/flavor_base/security_scan/packages/apt_get_packages_trivy_deps, flavors/standard-EXASOL-all-python-3.10/flavor_base/security_scan/Dockerfile, flavors/standard-EXASOL-all-python-3.10/flavor_base/security_scan/packages/apt_get_packages_trivy, flavors/standard-EXASOL-all-python-3.10/flavor_base/security_scan/packages/apt_get_packages_trivy_deps, flavors/standard-EXASOL-all-r-4.4/flavor_base/security_scan/Dockerfile, flavors/standard-EXASOL-all-r-4.4/flavor_base/security_scan/packages/apt_get_packages_trivy, flavors/standard-EXASOL-all-r-4.4/flavor_base/security_scan/packages/apt_get_packages_trivy_deps
=> #1135: use unpinned version of trivy

doc/changes/changes_9.6.0.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all-python-3.10/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/9.6.0/standard-EXASOL-all/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/standard-EXASOL-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-all/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #1141: Updated Dependencies on top of 9.5.2

.current_gitmodules, .github/workflows/slc_ci_check_for_build.yml, .github/workflows/slc_nightly.yml, doc/changes/changes_9.6.0.md, poetry.lock, pyproject.toml
=> Updated slc-ci and slc-ci-setup (#1174)

.current_gitmodules, doc/changes/changes_9.6.0.md
=> 1172: Removed old python2 tests

.current_gitmodules, doc/changes/changes_10.0.0.md, flavors/standard-EXASOL-all-java-11/flavor_base/release/Dockerfile, flavors/standard-EXASOL-all-java-17/flavor_base/release/Dockerfile, flavors/standard-EXASOL-all-python-3.10/flavor_base/release/Dockerfile, flavors/standard-EXASOL-all-r-4.4/flavor_base/release/Dockerfile, flavors/template-Exasol-all-r-4/flavor_base/build_steps.py, flavors/template-Exasol-all-r-4/flavor_base/release/Dockerfile
=> #1206: Trimmed release docker images

doc/changes/changes_10.0.0.md, doc/changes/package_diffs/10.0.0/standard-EXASOL-all-python-3.10/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/10.0.0/standard-EXASOL-all/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/standard-EXASOL-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-all/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #1213: Update Dependencies on top of 9.7.0

.current_gitmodules, doc/changes/changes_10.0.0.md, doc/changes/package_diffs/10.0.0/standard-EXASOL-all/flavor_base_deps_apt/apt_get_packages_diff.md, doc/changes/package_diffs/10.0.0/template-Exasol-8-python-3.10-cuda-conda/conda_deps/apt_get_packages_diff.md, doc/changes/package_diffs/10.0.0/template-Exasol-all-python-3.10-conda/conda_deps/apt_get_packages_diff.md, doc/changes/package_diffs/10.0.0/test-Exasol-8-cuda-ml/conda_deps/apt_get_packages_diff.md, flavors/standard-EXASOL-all/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #1223: Updated Dependencies on top of 9.7.0

doc/changes/changes_10.1.0.md
=> #1237: Fixed package diff link

.current_gitmodules, .github/markdown_check_config.json, doc/changes/changes_10.1.0.md, doc/changes/package_diffs/10.1.0/README.md, doc/changes/package_diffs/10.1.0/template-Exasol-all-python-3.12/build_deps/apt_get_packages_diff.md, doc/changes/package_diffs/10.1.0/template-Exasol-all-python-3.12/udfclient_deps/apt_get_packages_diff.md
=> #1260: Update locales dependencies

doc/changes/changelog.md, doc/changes/changes_10.1.0.md, pyproject.toml
=> Prepare release 10.1.0

doc/changes/changes_10.2.0.md, doc/changes/package_diffs/10.2.0/standard-EXASOL-all-python-3.10/flavor_base_deps/apt_get_packages_diff.md, doc/changes/package_diffs/10.2.0/standard-EXASOL-all/flavor_base_deps_apt/apt_get_packages_diff.md, flavors/standard-EXASOL-all-python-3.10/flavor_base/flavor_base_deps/packages/apt_get_packages, flavors/standard-EXASOL-all/flavor_base/flavor_base_deps_apt/packages/apt_get_packages
=> #1278: Updated Dependencies on top of 10.1.0
